//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationFormUser
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public state_table()
        {
            this.user_table = new HashSet<user_table>();
        }
    
        public int stateId { get; set; }
        public string state_name { get; set; }
        public int countryId { get; set; }
    
        public virtual country_table country_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_table> user_table { get; set; }
    }
}
