//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUserRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetails
    {
        public int ID { get; set; }
        public string email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string AddressLine1Permanent { get; set; }
        public string AddressLine2Permanent { get; set; }
        public string CityPermanent { get; set; }
        public int StatePermanent { get; set; }
        public int CountryPermanent { get; set; }
        public string ZipcodePermanent { get; set; }
        public string AddressLine1Present { get; set; }
        public string AddressLine2Present { get; set; }
        public string CityPresent { get; set; }
        public int StatePresent { get; set; }
        public int CountryPresent { get; set; }
        public string ZipcodePresent { get; set; }
        public string Password { get; set; }
    }
}
