//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProfileEntities : DbContext
    {
        public ProfileEntities()
            : base("name=ProfileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country_table> country_table { get; set; }
        public virtual DbSet<state_table> state_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
        public virtual DbSet<userroletable> userroletables { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<note> notes { get; set; }
    
        public virtual ObjectResult<getState_Result> getState(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getState_Result>("getState", idParameter);
        }
    
        public virtual ObjectResult<selectstate1_Result> selectstate1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectstate1_Result>("selectstate1");
        }
    }
}
