//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int Id { get; set; }
        public int objectID { get; set; }
        public string objectType { get; set; }
        public string objectNote { get; set; }
    }
}
