//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class state_table
    {
        public int stateId { get; set; }
        public string state_name { get; set; }
        public int countryId { get; set; }
    
        public virtual country_table country_table { get; set; }
    }
}
