//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class statelist_table
    {
        public int ID { get; set; }
        public string stateName { get; set; }
        public int countryID { get; set; }
    }
}
