//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsForYou.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgencyDetails()
        {
            this.AgencyFeed = new HashSet<AgencyFeed>();
            this.NewsDetails = new HashSet<NewsDetails>();
        }
    
        public int AgencyId { get; set; }
        public string AgencyName { get; set; }
        public string AgencyLogoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyFeed> AgencyFeed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsDetails> NewsDetails { get; set; }
    }
}
