//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsForYou.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsDetails
    {
        public int NewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDescription { get; set; }
        public System.DateTime NewsPublishDateTime { get; set; }
        public string NewsLink { get; set; }
        public int ClickCount { get; set; }
        public int CategoryId { get; set; }
        public int AgencyId { get; set; }
        public string NewsImageLink { get; set; }
    
        public virtual AgencyDetails AgencyDetails { get; set; }
        public virtual Category Category { get; set; }
    }
}
