//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsForYou.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsForYouEntities : DbContext
    {
        public NewsForYouEntities()
            : base("name=NewsForYouEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgencyDetails> AgencyDetails { get; set; }
        public virtual DbSet<AgencyFeed> AgencyFeed { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<NewsDetails> NewsDetails { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
    }
}
